spring:
  application:
    name: money-tracker
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
application:
  mode: prod
jwt:
  accessTokenExpiration: 60000
  secret: 25cf3c44c8f39313e8cbf7c23e22fe8b2ee8b288ee5206b0a6397583a1f7f0ef