logging:
  level:
    org.jetbrains.exposed.sql: DEBUG
    org.jetbrains.exposed.sql.statements: DEBUG
    org.jetbrains.exposed.sql.transactions: DEBUG
    jdbc.sqlonly: DEBUG
spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  docker:
    compose:
      file: docker-compose-local.yml
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5438/money-tracker-db
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: false
application:
  mode: local
jwt:
  accessTokenExpiration: ${JWT_TOKEN_EXPIRE_TIME:100000000000}
  secret: ${JWT_TOKEN_SECRET:ScoSHDpqKX3P9VgKC61rTdI0FrV1AvnVYugSXvqGM8X}
